SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")

SET(CPACK_PACKAGE_NAME "ElmerFEM-7.0")
SET(CPACK_PACKAGE_DESCRIPTION "[Dummy description]")
SET(CPACK_PACKAGE_FILE_NAME "dummy-elmerfem-7.0_Linux-x86_64")
SET(CPACK_PACKAGE_VENDOR "CSC")
SET(CPACK_PACAKGE_VERSION "${ELMER_FEM_MAJOR_VERSION}.${ELMER_FEM_MINOR_VERSION}")
SET(CPACK_PACKAGE_VERSION_MAJOR "${ELMER_FEM_MAJOR_VERSION}")
SET(CPACK_PACKAGE_VERSION_MINOR "${ELMER_FEM_MINOR_VERSION}")
#SET(CPACK_PACKAGE_VERSION_PATCH "0")

SET(CPACK_PACKAGE_CONTACT "elmeradmin@csc.fi")

#SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "Elmer Maintainer [dummy]")
#SET(CPACK_DEBIAN_PACKAGE_DESCRIPTION "Elmer fem description [dummy]")
#SET(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")

SET(CPACK_INSTALL_CMAKE_PROJECTS "$ENV{ELMER_BUILD_DIR};Elmer;ALL;/")
INCLUDE(CPACK)
