FROM ubuntu:xenial
RUN apt-get -y update && apt-get install -y gcc cmake g++ gfortran libopenblas-dev git
RUN apt-get install -y unzip libopenmpi-dev
RUN git clone https://github.com/ElmerCSC/elmerfem -b devel
ADD .stamp ./
RUN cd elmerfem && git pull
ADD precaches/opts-ubuntu-xenial.cmake /opts-ubuntu-xenial.cmake
RUN ls
RUN mkdir elmerbuild
WORKDIR elmerbuild
RUN cmake -C ../opts-ubuntu-xenial.cmake ../elmerfem
RUN make
RUN ctest 
