name: POC for mirroring and CICD on gitlab

on: [push, pull_request]

jobs:
  gitlabsync:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Gitlab mirror and CI"
        uses: "tiggi/gitlab-mirror-and-ci-action@tiggi/fixes"
        with:
          args: "https://gitlab.com/lumi-cicd/cicd_poc.git"
        env:
          FOLLOW_TAGS: "true"
          FORCE_PUSH: "true"
          GITLAB_HOSTNAME: "gitlab.com"
          GITLAB_USERNAME: "tiggi"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "50512004"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
